import { createRequestHandler, type ServerBuild } from "react-router";
// @ts-ignore — file is generated by `react-router build` and may not exist
//   on a fresh checkout. Wrangler bundles this entry; on a clean clone, run
//   `npm run build` once before `npm run typecheck`.
import * as build from "../build/server/index.js";

declare module "react-router" {
  export interface AppLoadContext {
    cloudflare: {
      env: Env;
      ctx: ExecutionContext;
    };
  }
}

const handleRequest = createRequestHandler(
  build as unknown as ServerBuild,
  "production",
);

export default {
  async fetch(request, env, ctx) {
    return handleRequest(request, { cloudflare: { env, ctx } });
  },
} satisfies ExportedHandler<Env>;
